# Generated by Django 4.1.3 on 2023-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_deliveryreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2cuploadproductmodel',
            name='crcProductUploadId',
            field=models.IntegerField(null=True),
        ),
    ]
