# Generated by Django 4.1.3 on 2023-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_c2cuploadproductmodel_crcproductuploadid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreport',
            name='user',
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='report',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
