# Generated by Django 4.1.3 on 2023-07-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_deliveryreport_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2cuploadproductmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='c2cuploadproductmodel',
            name='delivery_choice',
            field=models.CharField(choices=[('delivery_available', 'Delivery_Available'), ('not_available', 'Not Available')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='c2cuploadproductmodel',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='c2cuploadproductmodel',
            name='price_choice',
            field=models.CharField(choices=[('negotiable', 'Negotiable'), ('not_negotiable', 'Not Negotiable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='c2cuploadproductmodel',
            name='crcProductUploadId',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
