# Generated by Django 4.1.3 on 2023-08-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_c2cuploadproductmodel_approved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryReport',
        ),
    ]
