# Generated by Django 4.0.4 on 2022-06-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_product_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='Image_url',
            new_name='image_url',
        ),
    ]
