# Generated by Django 4.1.3 on 2023-08-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_deliveryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_delivery',
        ),
    ]
