# Generated by Django 5.0.2 on 2024-02-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_customuser_is_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='Department',
        ),
    ]
