# Generated by Django 4.0.4 on 2022-06-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
