# Generated by Django 4.0.4 on 2022-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
