# Generated by Django 4.0.4 on 2022-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Link',
            field=models.CharField(blank='True', max_length=200, null=True),
        ),
    ]
