# Generated by Django 4.0.4 on 2022-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='review',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
