# Generated by Django 4.0.4 on 2022-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_review_reviewrating_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='comment',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='rate',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
