# Generated by Django 4.0.4 on 2022-09-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_comment_reviewrating_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
