# Generated by Django 4.0.4 on 2022-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_order_unit_price_order_unit_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='Image',
            field=models.ImageField(default=1, upload_to='media/refund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
