# Generated by Django 4.0.4 on 2022-10-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_refund_image_refund_amount_refund_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/refund'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
