# Generated by Django 4.0.4 on 2022-10-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_refund_image_alter_refund_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='user',
        ),
    ]
