# Generated by Django 4.0.4 on 2022-10-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_refund_amount_remove_refund_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
    ]
