# Generated by Django 4.0.4 on 2022-10-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_order_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
