# Generated by Django 4.0.4 on 2022-11-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_post_view_count_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='media/profile.png', upload_to='media/blog'),
        ),
    ]
