# Generated by Django 4.0.4 on 2022-11-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='media/blog/profile.png', upload_to='media/blog'),
        ),
    ]
